media_dir : "/home/aroot/Desktop/puffer/media_dir"
enable_logging : false

channels: 
  - abc 
  # - praxo

channel_configs:
  abc:
    live: true
    video:
      1280x720: [23, 25]
      854x480: [23, 25]
    decoder_args: 240 189 720p60 120 900 10248 --tcp 127.0.0.1:5000  
    
    audio:
      - 64k
      - 32k
  # praxo:
  #   video:
  #     720p: [23, 25]
  #     480p: [23, 25]
  #   audio:
  #     - 64k
  #     - 32k
   
# wrapper:run_pipeline and atsc:decoder

# "Usage: " << program_name << " video_pid audio_pid format "
#   "frames_per_chunk audio_blocks_per_chunk audio_sample_overlap "
#   "video_output_dir audio_output_dir [--tmp TMP] [--tcp IP:PORT]\n\n"
#   "format = \"1080i30\" | \"720p60\"\n"
#   "--tmp TMP : output to TMP directory first and then move output chunks "
#   "to video_output_dir or audio_output_dir\n"
#   "--tcp IP:PORT : establish a TCP connection and read input from IP:PORT"



enable_logging: false
log_dir : "/home/aroot/Desktop/puffer/log_dir"
experiments: 
  node1: 
    num_servers: 1
    fingerprint: 
      cc: cubic
      # cc: bbr
      abr: mpc

portal_settings: 
  allowed_hosts: 
    - "127.0.0.1"
    - localhost
  debug: true
  secret_key: ")wyvs7qkr$8njj=@h+mv)r36z+g=#zd-s&1mupqc+@t=77n^(x"
postgres_connection: 
  dbname: puffer
  host: "127.0.0.1"
  password: 123456
  port: 5432
  user: amir
ws_base_port: 50041
