media_dir : "/home/amirsorouri00/Desktop/puffer_new/media_dir"
enable_logging : true

channels: 
  - abc 
  # - praxo

channel_configs:
  abc:
    video:
      1280x720: [23, 25]
      854x480: [23, 25]
    decoder_args: 240 189 720p60 20 20 10248 --tcp 127.0.0.1:5000  
    
    audio:
      - 64k
      - 32k
  # praxo:
  #   video:
  #     720p: [23, 25]
  #     480p: [23, 25]
  #   audio:
  #     - 64k
  #     - 32k
   
# wrapper:run_pipeline and atsc:decoder

# "Usage: " << program_name << " video_pid audio_pid format "
#   "frames_per_chunk audio_blocks_per_chunk audio_sample_overlap "
#   "video_output_dir audio_output_dir [--tmp TMP] [--tcp IP:PORT]\n\n"
#   "format = \"1080i30\" | \"720p60\"\n"
#   "--tmp TMP : output to TMP directory first and then move output chunks "
#   "to video_output_dir or audio_output_dir\n"
#   "--tcp IP:PORT : establish a TCP connection and read input from IP:PORT"